### ISSUE TITLE
Project Maintenance Inquiry

### ISSUE THREAD

**Issue by WengerK** [LionsAd/drupal_ti#118]
Hello @LionsAd 

Would you consider accepting some help to maintain and evolve drupal_ti ?

I found this project quite useful, especially while working with my own Drupal 8 contributions.
I would love to contribute some features and invest some time in triaging issues and reviewing PRs.

There hasn't been much movement here since at least Septembre 2018, so I am guessing you have moved one to other work and don't really use this project anymore.

So I am offering my time to work on issues, code and engage people to use and contribute.

Please let me know,
Kevin

**Comment by LionsAd** [comment]
Of course! I invited you as a contributor. Let me know if you need any other access / help.

And really sorry for not being more responsive. Drupal 7 core and real life (TM) took most of my remaining free time.

Greetings to Switzerland!

**Comment by LionsAd** [comment]
Btw. feel free to push, merge, triage, add features, etc.

I trust that you'll follow semver when releasing new versions - and if you can't just give me a ping and I'll do a new release.
