### ISSUE TITLE
Does this work with the new container-based infrastructure?

### ISSUE THREAD

**Issue by davereid** [LionsAd/drupal_ti#13]
http://docs.travis-ci.com/user/migrating-from-legacy/

> What are the restrictions? #
> 
> Using sudo isn’t possible (right now) #
> 
> Our new container infrastructure uses Docker under the hood. This has a lot of benefits like faster boot times and better utilization of resources. But it also comes with some restrictions. At this point, it’s not possible to use any command requiring sudo in your builds.
> 
> If you require sudo, for instance to install Ubuntu packages, a workaround is to use precompiled binaries, uploading them to S3 and downloading them as part of your build,then installing them into a non-root directory.
> 
> Databases don’t run off a memory disk #
> 
> On our legacy infrastructure, both MySQL and PostgreSQL run off a memory disk to increase transaction and query speed. This can impact projects making heavy use of transactions or fixtures.

**Comment by davereid** [comment]
It appears not to work. I tried adding `sudo: false` to a known passing module's .travis.yml and it failed: https://travis-ci.org/drupal-media/fallback_formatter/builds/70256756. Previous passing result: https://travis-ci.org/drupal-media/fallback_formatter/builds/70117588

**Comment by davereid** [comment]
So we'll want to ensure people are using `sudo: required` in their .travis.yml files now.

**Comment by LionsAd** [comment]
Yes, it works but only in a branch of this.

It might be they now allow to select packages for installation, that would make it simpler:

https://github.com/LionsAd/drupal_ti/tree/test-no-sudo

I got stuck with hhvm support at that time ...

But it should be simple to revive it for PHP 5.3-5.6.

**Comment by davereid** [comment]
Ok, so should we be ensuring `sudo: required` is in the default template right now? Because right now it will cause failures since Travis attempts to run the recommended branch on the new docker infrastructure.

**Comment by LionsAd** [comment]
Yes, I fear we need to do that :/

**Comment by LionsAd** [comment]
https://github.com/LionsAd/drupal_ti/blob/master/.travis.yml.dist#L11-L12

**Comment by davereid** [comment]
:+1: for preventing others from having the same confusion. Thanks so much for this really handy script. It's really nice from a module author perspective to not have to worry about so many specifics of getting TravisCI working.

**Comment by LionsAd** [comment]
Thanks, that means a lot from you, @davereid!

**Comment by LionsAd** [comment]
Closing in favor of https://github.com/LionsAd/drupal_ti/issues/18

**Comment by LionsAd** [comment]
Fixed in https://github.com/LionsAd/drupal_ti/pull/20.

@davereid sudo: required can be moved back to sudo: false again! :)
