### ISSUE TITLE
Build fails when a module has as a dependency on composer_manager module

### ISSUE THREAD

**Issue by cs-shadow** [LionsAd/drupal_ti#14]
When a module has a dependency on composer_manager, the build fails. It is basically stuck at this point:

```
The following projects have unmet dependencies:                      [ok]
url_embed requires composer_manager
Would you like to download them? (y/n): y
Install location /home/travis/build/drupal-media/drupal-8/drupal//modules/composer_manager already exists. Do you want to overwrite it? (y/n): 
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

Link to the relevant build in case you want to check: https://travis-ci.org/drupal-media/url_embed/jobs/70604609#L208

**Comment by cs-shadow** [comment]
It seems like the error will be generic to dependency to any module which already exists.

**Comment by davereid** [comment]
I don't believe this is an error with drupal_ti. I can reproduce this locally trying to enable the url_embed module without having the composer_manager module downloaded yet. I get stuck in a loop with Drush trying to download composer_manager:

```bash
davereid@davereidair /var/www/drupal8.dev/modules (8.0.x✓)$ drush pm-enable url_embed -y
The following projects have unmet dependencies:                                                                                                                      [ok]
url_embed requires composer_manager
Would you like to download them? (y/n): y
Project composer_manager (8.x-1.0-beta3) downloaded to /Users/davereid/Sync/projects/drupal8//modules/composer_manager.                                              [success]
Loading composer repositories with package information
Installing dependencies
Nothing to install or update
Generating autoload files
The following projects have unmet dependencies:                                                                                                                      [ok]
url_embed requires composer_manager
Would you like to download them? (y/n): y
Install location /Users/davereid/Sync/projects/drupal8//modules/composer_manager already exists. Do you want to overwrite it? (y/n): y
Project composer_manager (8.x-1.0-beta3) downloaded to /Users/davereid/Sync/projects/drupal8//modules/composer_manager.                                              [success]
Loading composer repositories with package information
Installing dependencies
Nothing to install or update
Generating autoload files
The following projects have unmet dependencies:                                                                                                                      [ok]
url_embed requires composer_manager
Would you like to download them? (y/n): y
Install location /Users/davereid/Sync/projects/drupal8//modules/composer_manager already exists. Do you want to overwrite it? (y/n):
```

**Comment by davereid** [comment]
So I can workaround this by just manually installing and enabling composer_manager before drupal_ti_ensure_module() is run. But the problem is that I need to do it in-between drupal_ti_install_drupal() and drupal_ti_ensure_module(), and there is not a point where I can inject custom code in there, from what I can tell.

The following fails due to `$DRUPAL_TI_DRUPAL_DIR` being empty since it hasn't been set yet.
```
before_script:
  # Manually enable and initialize composer_manager
  - cd "$DRUPAL_TI_DRUPAL_DIR"
  - drush dl composer_manager --yes
  - drush pm-enable composer_manager --yes
  - drush composer-manager-init
  - drupal-ti before_script
```

@LionsAd Can you please provide some guidance on how we can get composer_manager downloaded and installed in our tests without going through the Drush dependency loop (also filed as a bug against Drush)?

**Comment by davereid** [comment]
Actual Drush issue: https://github.com/drush-ops/drush/issues/5

**Comment by LionsAd** [comment]
@davereid Actually drupal_ti supports a full hook system:

Example:

- https://github.com/LionsAd/drupal_ti/blob/master/.travis.yml#L63-L66

- https://github.com/LionsAd/drupal_ti/tree/master/tests/drupal-8/drupal_ti_test/tests/drupal_ti/before/environments

In this case the easiest is to use a custom runner and add it before for simpletest:

e.g. like https://github.com/LionsAd/drupal_ti/blob/master/runners/simpletest/before_script.sh

However there clearly is a use-case to set dependencies directly and I will work on that tomorrow.

I think the MVP feature set is:

```
DRUPAL_TI_DRUPAL_MODULES=""
DRUPAL_TI_COMPOSER_DEPENDENCIES=""
```

and I am not yet sure about the syntax, but probably we need a way to get e.g. the md-systems fork of token module or such.

**Comment by LionsAd** [comment]
I think to get the DRUPAL_TI_DIR we should probably add a command, so that its simpler ...

**Comment by LionsAd** [comment]
@davereid Could you tell me which module with composer manager you use? Then I can do some experiments on my own ...

**Comment by cs-shadow** [comment]
@LionsAd Since you said that you would so some experiments, I'd like to point out a few things reg. url_embed as its a fairly new module and a lot of code is still buggy. There's no dependency on composer_manager yet, we removed it after the builds were failing.

PS: The PR which we were testing is this one: https://github.com/drupal-media/url_embed/pull/1. (There maybe some other things which are wrong with it as well)

**Comment by davereid** [comment]
I've been separately testing this in https://github.com/drupal-media/url_embed/pull/5 as well.

**Comment by LionsAd** [comment]
https://github.com/LionsAd/drupal_ti/pull/15

I am just waiting for tests to finish, then will merge this in.

Then it will be possible to easily include custom scripts running with all the drupal_ti vars set.

**Comment by LionsAd** [comment]
A work around using:

```
drupal-ti --include foo.sh
```

has been provided for now.

**Comment by cs-shadow** [comment]
@LionsAd Thanks for #15. I must say druapal_ti is a very neat and helpful project. Kudos to you!
