### ISSUE TITLE
Placeholder for Issue #2551981: Support --directory argument for run-tests

### ISSUE THREAD

**Issue by mradcliffe** [LionsAd/drupal_ti#40]
[Issue #2551981: Add --directory option to run-tests.sh test discovery](https://www.drupal.org/node/2551981).

This is not in Drupal core, but it could potentially cause issues. Just pinging you here so you're aware of the issue.

**Comment by LionsAd** [comment]
Thanks, hopefully BC will be preserved, so --group that drupal_ti uses by default should continue to work.

However if / when --directory is supported, someone could just add this to the arguments.

**Comment by LionsAd** [comment]
Closing for now.
