### ISSUE TITLE
What is the correct way to run PHPUnit KernelTestBase tests in modules?

### ISSUE THREAD

**Issue by slashrsm** [LionsAd/drupal_ti#50]
https://www.drupal.org/node/2489956 suggests
```
$ cd core
$ export SIMPLETEST_DB=mysql://root:@localhost/dev_d8; ./vendor/bin/phpunit --testsuite=kernel
```

I am currently using phpunit-core with SIMPLETEST_DB set in .travis.yml like this:

```
script:
  - drupal-ti --include .travis-phpcs.sh
  - export SIMPLETEST_DB=mysql://root:@127.0.0.1/drupal_travis_db; drupal-ti script
```

which, honestly, I don't really like but it works for now . :)

I was thinking about two options:
1. Update script.sh in phpunit-core to set environment variable correctly.
2. Create new runner for this kind of tests.

Which approach is correct?

**Comment by LionsAd** [comment]
I think the best would be if the environments/drupal-8.sh would set this variable from the DRUPAL_TI_DB_URL.
