### ISSUE TITLE
Behat example for Drupal 8?

### ISSUE THREAD

**Issue by stevector** [LionsAd/drupal_ti#57]
I'm having some trouble getting Behat to run in a contrib module for D8: https://github.com/stevector/template_mapper/pull/2 My last couple of commits have been switching the api driver between `drush` and `drupal`. I'm getting different errors with each.
 
Do you know of any contrib modules using drupal_ti that I could use as a comparison? I've looked at Panopoly but it seems like a much more advanced use case.

**Comment by LionsAd** [comment]
I don't know of any contrib modules, but drupal_ti tests itself, so:

https://github.com/LionsAd/drupal_ti/tree/master/tests/drupal-8/drupal_ti_test/tests/behat

might help to get started?

**Comment by LionsAd** [comment]
I think you will need to open an issue for https://github.com/jhedstrom/drupalextension as the https://github.com/jhedstrom/drupalextension/blob/master/src/Drupal/DrupalExtension/Context/RawDrupalContext.php#L466-L468 clearly tries to access ->role, which does not exist in Drupal 8 on the user object.

**Comment by stevector** [comment]
Thanks @LionsAd, I'll review the internal example more. I've got the tests running and passing locally without error. I'll do some more troubleshooting and follow up with drupalextension.

**Comment by LionsAd** [comment]
Using drupal-driver:dev-master fixes it for me on Drupal-8 with using drupal-driver, so closing for now.

Also of note:

Need to use 'standard' profile or any profile with a 'logout' link present on the front-page ('/').
