### ISSUE TITLE
Build error, requirements could not be resolved

### ISSUE THREAD

**Issue by kgaut** [LionsAd/drupal_ti#79]
Since a couple of days my build is errored each times, it seems that it's a requirement issue from drush :

```
Changed current directory to /home/travis/.composer

You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug

./composer.json has been updated

Loading composer repositories with package information

Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

  Problem 1

    - Installation request for drush/drush dev-master -> satisfiable by drush/drush[dev-master].

    - drush/drush dev-master requires codegyre/robo ~1.0.0-beta1 -> satisfiable by codegyre/robo[1.0.0-beta1] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

Error: /home/travis/.composer/vendor/lionsad/drupal_ti/runners/simpletest/install.sh exited with a failure.

The command "drupal-ti install" failed and exited with 1 during .

Your build has been stopped.
```
Don't have time to dig now, will do tomorrow.

full stack is visible here : https://travis-ci.org/mespronos/mespronos/jobs/129421306

**Comment by Roensby** [comment]
A discussion on the subject: http://drupal.stackexchange.com/questions/200539/drush-drush-dev-master-requires-codegyre-robo-1-0-0-beta1

**Comment by aweingarten** [comment]
+1 seeing the same issue. 
https://travis-ci.org/d8-contrib-modules/cloudflare/builds/130248819

**Comment by dsnopek** [comment]
I think if you used the dev-master version of drupal_ti you wouldn't see this issue since we've pinned Drush to a specific version, rather than using drush's dev-master release!

**Comment by kgaut** [comment]
In travis.yml replacing 

``` - composer global require LionsAd/drupal_ti:1.*```

by 

``` - composer global require LionsAd/drupal_ti:dev-master```

seems to fix it
