### ISSUE TITLE
Tag 1.4.3

### ISSUE THREAD

**Issue by bartfeenstra** [LionsAd/drupal_ti#80]
1.4.2 was released some time ago, and master contains some fixes that are necessary because of newer Drush releases. @LionsAd asked me to ping him in this issue.

**Comment by bartfeenstra** [comment]
@LionsAd Polite ping.

**Comment by LionsAd** [comment]
1.4.3 was just tagged, thank you for your patience.

I re-reviewed the diff and only bugfixes have been in this release.
