### ISSUE TITLE
Error running my first test

### ISSUE THREAD

**Issue by crevillo** [LionsAd/drupal_ti#81]
Hello. I'm having a problem running the test. You can see the error and the entire output at 
https://travis-ci.org/Tantacom/tantacom-web/jobs/134472696#L631

and my travis.yml file at https://github.com/Tantacom/tantacom-web/pull/5/files#diff-354f30a63fb0907d4ad57269548329e3R24

It looks like drupal is somehow installed two times... one under `/home/travis/build/Tantacom/tantacom-web/` and the other `/home/travis/build/Tantacom/drupal-8/drupal/`

any ideas of what could i be doing wrong?

**Comment by LionsAd** [comment]
Hello I am currently checking if master still passes tests. It might be 8.2.x related.

**Comment by crevillo** [comment]
thanks. But anyhow, now i thing it was i missunderstood the goal. In my repo i commited everything from core and my custom module too. And then, the script just does a git checkout from the drupal repo adding core files too and hence the error. 

Now i isolated my custom drupal module to their own repo, added the same travis.yml file and this error has gone away.

**Comment by crevillo** [comment]
And passing for me now!. https://travis-ci.org/Tantacom/tantaweb/jobs/134995635
i'm closing this. 
Anyway, i use to have core files and things like that on my own repo... so, questions here
1) is that a bad idea?
2) if not, is there a way to avoid the git checkout from drupal repo knowing core files are already there after the checkout of your own repo? 

Thanks a lot. great module btw.

**Comment by LionsAd** [comment]
Oh, yes. This is how it should be. Just the module! :)

**Comment by LionsAd** [comment]
In general it is a bad idea to commit core to your module.

**Comment by LionsAd** [comment]
If you want to use your module with core, you should have another repo with core and import your module via composer.json.

**Comment by crevillo** [comment]
i see. we'll is not i was trying to commit core to my module, why i was doing was commiting core to my repo and then adding my custom module. is that what you meant?

i was following, more or less this guide https://www.drupal.org/node/803746#code where "core" code is commited. is a guide for drupal 7 though
