### ISSUE TITLE
Module linking with composer means travis test wrong branch

### ISSUE THREAD

**Issue by yanniboi** [LionsAd/drupal_ti#98]
I am using travis to test changes to my Drupal module before merging them back into 8.x-1.x. 

However I think that since environments/drupal-8.sh **drupal_ti_ensure_module_linked()** now gets the module from composer using '*@dev', rather than using the commit of the module that I am actually testing, it always gets a release version (eg alpha-1) from drupal.org. 

Why is this better than using **drupal_ti_ensure_module_linked()** as defined in functions/drupal.sh which uses the commit checked out by travis?

**Comment by yanniboi** [comment]
Ok, so I have realised that actually using composer is quite useful because it allows any other dependencies to be included. However I think composer is getting confused between the two available repos (the drupal.org one and the path one) and therefore getting the wrong 'version'?

At any rate is there a way of getting the commit id from a travis (TRAVIS_COMMIT I think) and telling composer to specfically checking out that commit (eg "dev-master#TRAVIS_COMMIT")?

**Comment by yanniboi** [comment]
Also is anyone else having my problem?

**Comment by yanniboi** [comment]
Ok, taking this issue back. I think there was something weird going on with composer manager. I rebuilt my test stack using after script directories to tweak **drupal_ti_ensure_module_linked** and **drupal_ti_install_drupal** to allow patching and now it works fine!

**Comment by subhojit777** [comment]
@yanniboi I am also having the same problem but with Drupal 8. Can you tell me what you did that fixed the problem.

**Comment by subhojit777** [comment]
I was incorrectly requiring a submodule's composer.json into the main module. And it was messing up the process. After removing that, drupal_ti was symlinking the module/package as expected.
